### ISSUE TITLE
Fill out actual content in thanks component

### ISSUE THREAD

**Issue by sreynen** [MoveOnOrg/mop-frontend#12]
Currently it's just `Thanks Yo! {petition.petition_id}`. Update to match legacy thanks page content.
 - [x] pass `id=` and `source=` parameters from url OR state into tweet/facebook links
 - [x] make sure [sharebandit](https://github.com/MoveOnOrg/sharebandit) support is still possible/works
 - [x] mobile view
 - [x] email body needs `petition.about` and `petition.statement` and megapartnet/creator/signor values
 - [x] facebook pixel loading for analytics
 - [x] google 'pagead' pixel loading for analytics?
 - [x] next petition value loading

**Comment by schuyler1d** [comment]
closing since this work was completed, and other bugs/issues should be individual tickets.
