### ISSUE TITLE
Padding Pushing Recent Victories Component Down

### ISSUE THREAD

**Issue by shakalee14** [MoveOnOrg/mop-frontend#121]
<img width="1112" alt="screen shot 2017-12-13 at 10 43 21 am" src="https://user-images.githubusercontent.com/16676323/33947569-b378e2f8-dff2-11e7-927e-205858321199.png">

could be fixed by overriding some widget styling in moui.css

`.widget {
    /* padding: 10px 7px 0 7px; */
    margin-bottom: 30px;
}`

<img width="1197" alt="screen shot 2017-12-13 at 10 43 28 am" src="https://user-images.githubusercontent.com/16676323/33947571-b7e4a0c0-dff2-11e7-9b8f-9829c4216be4.png">

**Comment by shakalee14** [comment]
i don't see this behavior locally

**Comment by schuyler1d** [comment]
I believe this is related to the moui.css having css related to `<body class="moveon-petitions ">` on the homepage.  However the React architecture doesn't allow us to modify the body element. so as we did with the petition signing page, we need to find places with `body.moveon-petitions` in `css/moui.css` and add a rule in that version of `div.moveon-petitions` (after some research just to confirm that class="moveon-petitions" is only on moveon homepage (probably)).

**Comment by sreynen** [comment]
Here's a list of all the body classes in `moui.css` and where I was able to find them in use on petitions.moveon.org:

- **home**: _not used_
- **blog**: _not used_
- **sign**: sign pages
- **moveon-petitions**: all pages
- **confirm**: create petition preview page
- **share**: thanks pages
- **review**: all pages under /review/ (not currently in scope)
