### ISSUE TITLE
Update all assets to be https secure

### ISSUE THREAD

**Issue by schuyler1d** [MoveOnOrg/mop-frontend#137]
https://github.com/MoveOnOrg/mop-frontend/blob/master/src/components/recentvictory.js
has a lot of img sources that are insecure.  All of these should be switched to https.

Ideally all links and protocol references to `http://` shoud be updated to `https://`

**Comment by jparkrr** [comment]
I believe you closed this with https://github.com/MoveOnOrg/mop-frontend/pull/167, yes?

**Comment by schuyler1d** [comment]
yes, thanks
