### ISSUE TITLE
Make login form POST login credentials to API, recieve auth cookie

### ISSUE THREAD

**Issue by sreynen** [MoveOnOrg/mop-frontend#148]
Submitting login form should log you in. Blocked on #147.

**Comment by jparkrr** [comment]
Shouldn't be blocked anymore due to #232

I'll have a look at the API for login, but any pointers are appreciated.

**Comment by jparkrr** [comment]
Looks like the API will be implemented in https://github.com/MoveOnOrg/mop/issues/124

**Comment by schuyler1d** [comment]
This is implemented in branch `auth-phase-2` (https://github.com/MoveOnOrg/mop/pull/287)
I'm not going to merge ot main until we have a branch on mop-frontend that we can test together.  The api points are: `/api/v1/user/session/login` and `logout`.  Login is a json api with `{"username": "email@example.com", "password": "foobar"}` That creates a cookie.

There is still an outstanding CSRF issue for petition creation (and probably other related forms), but login/logout should be doable now.
