### ISSUE TITLE
Make footer links respond to login status

### ISSUE THREAD

**Issue by sreynen** [MoveOnOrg/mop-frontend#172]
We're updating header links based on login status, but footer links do not yet update. Looks like we have the logged-in links hard-coded, so "Logout" needs to be "About" when logged out, and "Dashboard" needs to be "Manage Petitions." Also, when logged in, "Dashboard" should be "{name}'s Dashboard."

**Comment by schuyler1d** [comment]
Possibly late, but I would like to argue for a stateless header for better consistency across sites, and the fact that both the inconsistency and the unlikely location makes footer links pointless.

**Comment by sreynen** [comment]
Confirmed this isn't needed, closing.
