### ISSUE TITLE
Logo is wrong

### ISSUE THREAD

**Issue by sreynen** [MoveOnOrg/mop-frontend#173]
I'm not sure how we ended up with the wrong logo, and that's probably worth some research to see if there's a context in which the logo changes. But the most common logo on the live site, https://petitions.moveon.org, is "MoveOn.org Petitions," which is different than the "MoveOn.org Democracy in Action" logo we're currently using everything.

**Comment by sreynen** [comment]
Note: footer logo is also wrong.

**Comment by shakalee14** [comment]
locally - i see the correct images (compared to petitions.moveon.org)
- MoveOn.org Petitions logo in the nav
- MoveOn.org Democracy in Action logo in the footer

broom - i see the incorrect image in the nav (compared to petitions.moveon.org)
- MoveOn.org Democracy in Action logo in the nav
- MoveOn.org Democracy in Action logo in the footer

and production -
- MoveOn.org Petitions logo in the nav
- MoveOn.org Democracy in Action logo in the footer

**Comment by sreynen** [comment]
Looks like I got the footer logo part wrong, meaning that's actually correct. I'm seeing different results between local loaded from Django app vs. frontend `npm run dev`. I don't know where exactly the difference is, and it's possibly a backend issue, but Django app still loads the React app, so could still be a frontend issue.
