### ISSUE TITLE
Font is wrong

### ISSUE THREAD

**Issue by sreynen** [MoveOnOrg/mop-frontend#174]
The fonts between the live site and test instance are very similar, but different. The clearest difference is a lowercase "l", which has a little curl on the live version, but no curl on the test. But the bigger, though less clear, difference is the size is slightly different, which shifts sizing on everything, making it hard to compare live to test.

**Comment by shakalee14** [comment]
Yea i think the font size is possibly the same but the font is different. I made a note of this earlier and was wondering if it was based on some connection to google fonts. I sometimes get a message that google is going to use a fallback font due to slow connectivity.

**Comment by sreynen** [comment]
After way too long trying to track down the difference in CSS, realized it's actually a much simpler difference in the HTML. Specifically, the font was entirely missing from the HTML.
