### ISSUE TITLE
Megapartner url does not include megapartner name

### ISSUE THREAD

**Issue by shakalee14** [MoveOnOrg/mop-frontend#176]
For example:

We should keep the same pattern --> 

Real URL: https://petitions.moveon.org/workingfamilies/sign/censure-trump-for-refusing

Dev/stage URL that works: 0.0.0.0/workingfamilies/sign/censure-trump-for-refusing 

Dev/stage URL that does not work but should work: 0.0.0.0/sign/censure-trump-for-refusing

**Comment by schuyler1d** [comment]
https://github.com/MoveOnOrg/mop/pull/129 will fix the 404 at the new url in staging

I'm tempted to say that it's not important to redirect this, even though that's the old behavior, as long as both links work.  I'd like to get Platform's feedback, on the importance.

**Comment by schuyler1d** [comment]
Turns out this is an issue because the logo doesn't show up.  Frontend should redirect upon seeing a megapartner

**Comment by jparkrr** [comment]
Is this the same as https://github.com/MoveOnOrg/mop-frontend/pull/303, or different somehow?

**Comment by sreynen** [comment]
I think this is the same as #193, which is closed now, so closing this.
