### ISSUE TITLE
Sign page is missing disclaimer text

### ISSUE THREAD

**Issue by sreynen** [MoveOnOrg/mop-frontend#184]
Should say "Note: MoveOn Civic Action does not necessarily endorse the contents of petitions posted on this site. MoveOn Petitions is an open tool that anyone can use to post a petition advocating any point of view, so long as the petition does not violate our terms of service."

Or on PAC petitions: "Note: MoveOn Political Action does not necessarily endorse the contents of petitions posted on this site. MoveOn Petitions is an open tool that anyone can use to post a petition advocating any point of view, so long as the petition does not violate our terms of service."

(Note text styling on live site.)

**Comment by schuyler1d** [comment]
Please provide an example petition when you don't see expected pieces /wording

**Comment by sandramchung** [comment]
The terms of service page still needs to be created. Opening a new issue for it
