### ISSUE TITLE
Target descriptions should not be abbreviated

### ISSUE THREAD

**Issue by sreynen** [MoveOnOrg/mop-frontend#185]
E.g. /sign/georgia-add-outkast-to says "Gov. Nathan Deal, The GA State House, The GA State Senate" but should say " The Georgia State House, The Georgia State Senate, and Governor Nathan Deal"

**Comment by sandramchung** [comment]
This is a backend fix - PetitionTarget model should return the full name of the state in the statehouse case and the full title of the Governor in the governor case.

**Comment by jparkrr** [comment]
I just found out that we already have this in the frontend https://github.com/MoveOnOrg/mop-frontend/blob/master/src/components/state-abbrev.js

Used a couple of places https://github.com/MoveOnOrg/mop-frontend/search?utf8=✓&q=state-abbrev&type=

**Comment by sreynen** [comment]
I think we should still fix this on the back end. The API sends targets back as strings like "The GA State House." We could probably find and replace the abbreviation in a string like that, but doing so would require the front end to know what the back end might send, and then require updating both together as we make future changes, e.g. we might at some point stop referring to "Nebraska State House" and "Nebraska State Senate" as targets, because Nebraska doesn't actually have a separate house and senate.

**Comment by jparkrr** [comment]
https://github.com/MoveOnOrg/mop/pull/223
