### ISSUE TITLE
Remove "Send a link:" on thanks page

### ISSUE THREAD

**Issue by sreynen** [MoveOnOrg/mop-frontend#188]
I'm not sure where this came from, so maybe this needs more discussion, but current request is to remove it.

**Comment by schuyler1d** [comment]
Yes please -- this increases usability and makes debugging much easier.  It drives me crazy that I can't get a link from the thanks page to the petition, 'raw' (rather than the whole body of an email, e.g., etc).

If we must, then let's hide it for now, rather than delete.

**Comment by shakalee14** [comment]
handled with https://github.com/MoveOnOrg/mop-frontend/commit/c09d9e17a55dc359087bd94181cb8e284058dd2f
