### ISSUE TITLE
Hide most navigation on create petition page

### ISSUE THREAD

**Issue by sreynen** [MoveOnOrg/mop-frontend#201]
This is split off from #55. Notes from there:

- have the nav display handled with redux - we usually hide the nav when we don't want it to distract from the action featured on the page

**Comment by shakalee14** [comment]
Looks like this issue is related:
https://github.com/MoveOnOrg/mop-frontend/issues/63

**Comment by schuyler1d** [comment]
ok, i'll tackle both
