### ISSUE TITLE
Validate and submit petition create form step 1

### ISSUE THREAD

**Issue by sreynen** [MoveOnOrg/mop-frontend#203]
Validation can probably copy a lot from how signature form does validation. When validation succeeds, the form values should save in redux and then move to step 2, which is covered in #339.

**Comment by jparkrr** [comment]
@shakalee14 I have a refactor of the petition create stuff in https://github.com/MoveOnOrg/mop-frontend/pull/279. Sorry that it might conflict with the things you have locally for this. Let me know if you want me to take this over.

**Comment by jparkrr** [comment]
Further work depends on https://github.com/MoveOnOrg/mop/issues/284
