### ISSUE TITLE
Track load time

### ISSUE THREAD

**Issue by sreynen** [MoveOnOrg/mop-frontend#207]
This is in theory already happening with Google Analytics, but that's not working and we need to make sure it is working before launch. Once it's working on the legacy site, need to make sure it works just as well on new site.

**Comment by sreynen** [comment]
I think this is working on the legacy site, so no longer blocked, but check with @lady3bean on that and how to test this.

**Comment by mathemagica** [comment]
GA tracks this

**Comment by sreynen** [comment]
We're seeing realistic-seeming numbers in GA now, so closing this.
