### ISSUE TITLE
Need clearer distinction between search hasn't started and zero results

### ISSUE THREAD

**Issue by sreynen** [MoveOnOrg/mop-frontend#210]
Currently when search page first loads, it looks like this:
<img width="137" alt="screen shot 2018-01-30 at 4 06 53 pm" src="https://user-images.githubusercontent.com/108645/35596563-a3b1ff2a-05d7-11e8-9ec8-0ef4c5b145bc.png">

That changes to actual results as soon as they come in, but if there's any delay in getting results, it looks like there are no results, and people may close before the results load. It should instead give some indication that results are still loading.

**Comment by schuyler1d** [comment]
if we have a general 'loading' treatment it would also be good to render in some other contexts like while a petition loads.  Any chance the rebrand has a loading icon we could backport? ^_^

**Comment by sandramchung** [comment]
I added a "Loading ..." state. Now figuring out how to get search results to come in slowly enough for me to test it.
