### ISSUE TITLE
query-string should not be a dependency

### ISSUE THREAD

**Issue by schuyler1d** [MoveOnOrg/mop-frontend#235]
remove query-string from
 src/components/state-check-box.js
(which breaks tests when I run it)
and instead of parsing query string, we should use the `props.query` parameter in that component already passed

**Comment by 6ewis** [comment]
I couldn't reproduce the test breaking - it ran fine with query-string. However, I updated it to use props.query https://github.com/MoveOnOrg/mop-frontend/pull/252 .
