### ISSUE TITLE
Make home page example component set switch

### ISSUE THREAD

**Issue by sreynen** [MoveOnOrg/mop-frontend#256]
We've started moving some components to src/components/legacy in anticipation of having new versions of those same components with new designs that use slightly different HTML but mostly function the same. The task here is to work out how we're going to switch between these component sets, using the home page as an example.

Ideally we'd be able to change a single variable (maybe a parameter on the route?) and make everything on the home page start using components from src/components/giraffe instead of src/components/legacy. It would also be great if we could keep the initial load size smaller by lazy-loading those components, so we're not loading components from both sets when we're only using one set.

**Comment by jparkrr** [comment]
I think it's worth considering a simple option, which is just to manually change the import statements from `import ./legacy/whatever` to `import ./giraffe/whatever`.

This fits the requirement of not including the legacy components in the bundle, because unused components will then no longer be referenced.

**Comment by jparkrr** [comment]
Do we want to do any A/B testing of old vs new design?

**Comment by sreynen** [comment]
We will want to do A/B testing, but the split for that won't need to be done in React. We'll be segmenting the A/B audiences by pointing them at different URLs, so the backend can load separate JS builds.

I think that means switching the imports works, but because we'll want to run both builds at the same time during testing, doing that switch manually doesn't sound great. I think ideally we'd be able to run something like `npm run build-legacy` and `npm run build-giraffe` and get two builds with separate component sets, and then maybe make an update to some container and run both again to apply that update to both builds.

I know @schuyler1d has put some thought into this. Anything to add?

**Comment by jparkrr** [comment]
Makes sense. 

One idea is:
```import ./giraffe/whatever``` in the code (you have to change it once to opt into the new component for this page)

and `npm run build-legacy` could add a module resolve alias for `giraffe` -> `legacy` so it builds with legacy components (alt. aliasing something neutral like `_THEME_`)

as well as `npm run dev-legacy` to test (as well as staging of course)

**Comment by jparkrr** [comment]
Here are the docs for resolve alias: https://webpack.js.org/configuration/resolve/#resolve-alias

**Comment by schuyler1d** [comment]
I'd been thinking of setups where we support multiple skins in the same app, but the advantage to two builds is that the react app for each will be the 'right size' for the eventual deployment, so neither is overly slowed down.

This will make a more complex routing story and backend story, but this is a lot simpler than what i was imagining (basically decorating different <Route>s with some bag-of-components object that represents the style).

So I'm pretty ++ on webpack resolve-alias mode.  We should probably sketch out the consequences a bit more on deployment (e.g. how can we standardize the url-routing to the deployed static files)
