### ISSUE TITLE
Proposal to use main app with static pages

### ISSUE THREAD

**Issue by schuyler1d** [MoveOnOrg/mop-frontend#263]
mop-static pages load html and the nav of this app.  But that means that moving from static content to the new app will be slow and load a completely different react app and state when moving across.   This is a good strategy while the majority of pages/visits are served by the legacy html server.  However, as we move to more sites on the new, we should try to bridge this gap.

I propose the following:
* whitelist static page routes in one 'page' container component in react routes -- e.g. for `about.html` and `privacy.html` both would have StaticPage a la  `<Route path='/about.html' component={StaticPage} />`
* The StaticPage will load json from converted versions in mop-static, similar to: https://github.com/MoveOnOrg/mop-static/blob/json-for-react/about.json
* there will be a STATIC_PAGES_BASEURL variable which is where it will fetch the json based on the path.

assigning to @sreynen for evaluation/decision but all welcome to weigh in.

**Comment by sreynen** [comment]
I like the idea of loading the content via API. I'd also like to keep the content editable as HTML, so non-tech staff can potentially do the edits. One way to accomplish that would be to run some sort of HTML-to-JSON script whenever updates are made, generating the JSON. But in thinking about this, I realized we already have a system that makes HTML easy to edit and wraps it in a JSON API: our WordPress site.

I hadn't looked at the WordPress API in much detail before, but looking at it now (e.g. https://front.moveon.org/wp-json/wp/v2/posts/60904) I think it could work for this. So counter-proposal: let's move all static page content into unlinked WordPress pages, and then load it via the WordPress API.

Thoughts?

**Comment by schuyler1d** [comment]
Yes, ++ to doing it in WordPress -- that's a great idea and then gets us out of the job of managing/editing html content, and will hopefully keep these pages fresher.  The other cool part of this is there's at least one page we might want to 'cross post' -- the privacy policy is on the wordpress site now, but if we could always load it from react, then we don't have to move the person out of the react app and also ensure it's the same up-to-date content.

**Comment by schuyler1d** [comment]
The one thing we need is to either proxy this under the CDN or tweak the CORS headers. -- though  WP might have a callback= parameter supported too

**Comment by jparkrr** [comment]
I'll start working on a static page page component that can load JSON from Wordpress.

**Comment by sreynen** [comment]
This plan has been run by everyone involved with no flags, so closing this issue and opening implementation tasks.
