### ISSUE TITLE
Remove padding under video

### ISSUE THREAD

**Issue by sreynen** [MoveOnOrg/mop-frontend#284]
Currently the following contexts have some padding under the video:

- broom.moveon.org in Firefox
- broom.moveon.org in Chrome
- broom.moveon.org in Safari
- petitions.moveon.org in Firefox
- petitions.moveon.org in Safari

And this context has no such padding:

- petitions.moveon.org in Chrome

So this is technically a regression, but only in Chrome. Ideally we could go beyond fixing it in Chrome and remove the padding in all browsers.

**Comment by jparkrr** [comment]
Looks like something about the `clearfix`  is causing this. I haven't fully figured it out though.
