### ISSUE TITLE
PAC petitions before rebrand is fully deployed

### ISSUE THREAD

**Issue by schuyler1d** [MoveOnOrg/mop-frontend#297]
Right now we have siphoned off PAC to a different CDN that is only touching the legacy system.  However, when we switch to the rebrand we will actually need to address this.

Tracking issue on the backend here: https://github.com/MoveOnOrg/mop/issues/194

**Comment by sreynen** [comment]
I created individual issues in https://github.com/MoveOnOrg/mop-frontend/milestone/15 so closing this.
