### ISSUE TITLE
Signing doesn't yield r_hash or r_by links in e.g. email message

### ISSUE THREAD

**Issue by schuyler1d** [MoveOnOrg/mop-frontend#301]
Steps to reproduce:
1. https://broom.moveon.org/sign/georgia-add-outkast-to
2. sign the petition. you get to https://petitions.moveon.org/thanks.html?petition_id=95983&name=georgia-add-outkast-to
which doesn't have an r_by.

Actually, I think this is because broom doesn't have `prodReady` on thanks, and so it moves to petitions.moveon.org instead of *broom.moveon.org`'s version of thanks page.

**Comment by jparkrr** [comment]
So is the idea that, while `Thanks` isn't prodready, if you sign the petition at `https://broom.moveon.org/sign/georgia-add-outkast-to?r_id=something`, you should get forwarded to `https://petitions.moveon.org/thanks.html?petition_id=95983&name=georgia-add-outkast-to&r_id=something`?

**Comment by jparkrr** [comment]
I guess easiest is if we are able to mark the Thanks page prodReady, as that is where all this logic was moved.

**Comment by sreynen** [comment]
This was discussed in chat, but to close the loop here, no reason we can't mark Thanks as prodReady, as it is only ever reached via the sign page.

**Comment by jparkrr** [comment]
Is this ok to leave closed now? Or do we want to verify that share tracking is working correctly?
