### ISSUE TITLE
Create container, component, redux store, load actions, etc. for static pages

### ISSUE THREAD

**Issue by sreynen** [MoveOnOrg/mop-frontend#306]
Based on discussion in https://github.com/MoveOnOrg/mop-frontend/issues/263, we're going to change the way we're loading pages with static (non-interactive) content. We've been loading them as static HTML from S3, but we're going to switch to loading them within React from the WordPress API.

Here's an incomplete list of all the pages we need to add and their API endpoint:

- http://petitions.moveon.org/about.html => https://front.moveon.org/wp-json/wp/v2/pages/60931
- http://petitions.moveon.org/campaign_tips.html => https://front.moveon.org/wp-json/wp/v2/pages/60942
- http://petitions.moveon.org/funding.html => https://front.moveon.org/wp-json/wp/v2/pages/60943
- http://petitions.moveon.org/howto_campaign.html => https://front.moveon.org/wp-json/wp/v2/pages/60944
- http://petitions.moveon.org/howto_communication.html => https://front.moveon.org/wp-json/wp/v2/pages/60945
- http://petitions.moveon.org/howto_delivery.html => https://front.moveon.org/wp-json/wp/v2/pages/60946
- http://petitions.moveon.org/howto_petition.html => https://front.moveon.org/wp-json/wp/v2/pages/60947
- http://petitions.moveon.org/howto_twitter.html => https://front.moveon.org/wp-json/wp/v2/pages/60948
- http://petitions.moveon.org/organizations.html => https://front.moveon.org/wp-json/wp/v2/pages/60949
- http://petitions.moveon.org/privacy.html => https://front.moveon.org/wp-json/wp/v2/pages/60950
- http://petitions.moveon.org/terms.html => https://front.moveon.org/wp-json/wp/v2/pages/60951

I will update that list as I add more pages to WordPress, and possibly discover more pages that should load like this.

This will likely require changes to CORS headers on the front.moveon.org side, and I'll try to get that done before it becomes a blocker.

**Comment by jparkrr** [comment]
@sreynen http://petitions.moveon.org/campaign_tips.html links to http://www.petitions.moveon.org/help.html

which brings up another question of how links should work, but I'll bring that up somewhere else
