### ISSUE TITLE
Update page <title> as route changes

### ISSUE THREAD

**Issue by sreynen** [MoveOnOrg/mop-frontend#315]
For static pages, title comes from API. For everything else, maybe just hard-code them?

**Comment by schuyler1d** [comment]
maybe make it a property on the page container and then update the title inside this code function:
https://github.com/MoveOnOrg/mop-frontend/blob/main/src/routes.js#L42

**Comment by jparkrr** [comment]
@schuyler1d I don't think that would work in the cases that we haven't loaded the data needed to construct the title.

I'll try using https://github.com/gaearon/react-document-title, which allows you to specify it in the `render()` in a declarative way, which sounds like the right way to me.

I would normally reach for https://github.com/nfl/react-helmet but, unless we want to set meta tags as well, I'll use the smaller dependency.
