### ISSUE TITLE
Petition share links for redesign

### ISSUE THREAD

**Issue by schuyler1d** [MoveOnOrg/mop-frontend#327]
On the thanks page, share links should be carried over from the legacy implementation.  Note that share links on that version are calculated partially from data gotten from the signature POST.

On the petition page itself, the new design includes four links:
 - [x] Facebook share - if there is a sharebandit url, upon clicking the link it should get `getSharebanditShareLink` the same way the thanks page does (ideally not before).  If there is no sharebandit link, it should be the standard facebook petition link, but with `source=n.fb.p` where `n` is for "non-signer" and `.p` is for the petition page.  Note that if the client 'knows' that the user is the creator or has signed the petition, then you can/should replace `n.` with either `c.` or `s.` appropriately
 - [x] Twitter share - This should use the lib `petitionShortCode` url, with mode=`n`.  Note that if the user is logged in or has guest credentials (e.g. akid, etc), then you can/should pass in the userId
 - [x] Email share - This will be the same thing as the thanks page except the link will be `source= n.mt.p` (unless it's meant to be copy-pasted, in which case n.cp.p)
 - [x] Copy Link share should be the same think as rawShareLink but with mode=`m` for a non-signer (keep the other two, if they are known creator/signers, but don't hit an additional api to find out).

See [this PR](https://github.com/MoveOnOrg/mop/pull/235) and the full shortcodes file for short-code related questions. 

Also update docs/EXPLANATION-share-links.md

**Comment by jparkrr** [comment]
For the sign page we might want a slight rephrasing of the mail message, it currently says

> That's why I **signed** a petition to President Donald Trump, The United States House of Representatives, and The United States Senate, which says:

**Comment by jparkrr** [comment]
For email share on the thanks page we have something like `source=s.em.mt`. Did you drop "em" on purpose above for the petition page? If I kept it, it would be like `n.em.mt.p`

**Comment by schuyler1d** [comment]
that was a mistake.  do `n.em.mt.p`

**Comment by jparkrr** [comment]
Thanks! Last question I think: should we also `recordShareClick()` for the sign page?
