### ISSUE TITLE
Add create_preview.html route, container, and component

### ISSUE THREAD

**Issue by sreynen** [MoveOnOrg/mop-frontend#339]
This should generally look like the current version, but the data flow will be different. The current version saves step 1 on the server, then creates an account in step 2 and makes that account the creator. The new version will do the opposite. Step 1 will save the petition in redux. Then on step 2, if the creator is not already authenticated, we'll create the account before submitting the petition.

The petition creation API is `user/petitions` and it takes a JSON POST body with a `petition` key on an object that maps key/value pairs to the form inputs from create_start (step 1).

The user creation API is `user` and it takes a JSON POST body with a `user` key on an object that maps key/value pairs to the form inputs on the current create_preview, with the exception of `password_confirm`, i.e. `name`, `email`, `phone`, `zip`, and `password`.

**Comment by jparkrr** [comment]
Work in progress is on this branch https://github.com/MoveOnOrg/mop-frontend/tree/339-create-preview

unassigning myself until I have time to work on this again

**Comment by jparkrr** [comment]
Well, the preview part is done, but this also includes submitting, which isn't done.

**Comment by jparkrr** [comment]
Splitting the remaining work into this issue https://github.com/MoveOnOrg/mop-frontend/issues/551
