### ISSUE TITLE
Add session awareness to nav.js

### ISSUE THREAD

**Issue by sreynen** [MoveOnOrg/mop-frontend#34]
When logged in, "EDIT ACCOUNT" and "LOGOUT" links should be added. Also, currently "MANAGE PETITIONS" link changes to "{firstname}'S DASHBOARD" on legacy site, but not sure whether or not new design intends to maintain that switch.

If we can't do this entirely client-side with the current login process (e.g. by reading a cookie), this issue should maybe be deferred until we have a new login process.

**Comment by shakalee14** [comment]
i think this issue needs login & sign up routes first? but maybe not?

**Comment by schuyler1d** [comment]
@shakalee14 https://github.com/MoveOnOrg/mop-frontend/pull/65 should provide session state which you can use in nav, as well.  (just testing `store.userStore.signonId` as long as you've hooked the component up to redux)
