### ISSUE TITLE
on /2018/ urls session.json is called for each page visit (should only be initial load)

### ISSUE THREAD

**Issue by schuyler1d** [MoveOnOrg/mop-frontend#348]
Go to /2018/ click on a petition.  Note that two session.json calls are made.  I believe we should only make the initial one.

**Comment by jparkrr** [comment]
I think this comment is incorrect and even the root `onEnter` is called for every navigation push
https://github.com/MoveOnOrg/mop-frontend/blob/0057fd2cadebd572cab14bd829012fcb48727528/src/actions/sessionActions.js#L58

so perhaps if there's already a session in redux we can not call the api?

**Comment by jparkrr** [comment]
or actually it's probably better to find a way to just fire loadSession once. Perhaps some componentDidMount? We could either create routes.js into a class or stick it in Wrapper. (I'd prefer the first one)

**Comment by schuyler1d** [comment]
no preference on my side.  Also ok with something like a `forceRefresh` option for loadSession and then you test against the existing store data.
