### ISSUE TITLE
Font sizes for mobile petition and thanks page

### ISSUE THREAD

**Issue by schuyler1d** [MoveOnOrg/mop-frontend#351]
I got a report on Friday

1. Font size and style of state and zip code are different. 
2. Email share button is sized differently than Facebook and Tweet buttons. 

I haven't verified this, but before I manage to do so or get screenshots from the reporter wanted to put it in here.

**Comment by jparkrr** [comment]
I see what they're saying, but it's the same as legacy
![screen shot 2018-03-16 at 3 28 11 pm](https://user-images.githubusercontent.com/872456/37540807-b13b3bfa-292e-11e8-8573-6962d7bdd123.png)
![screen shot 2018-03-16 at 3 28 46 pm](https://user-images.githubusercontent.com/872456/37540815-be3f6cb8-292e-11e8-81c8-af05ac187b09.png)

**Comment by sreynen** [comment]
Closing this. I would move it to post-launch list, but redesign will make it irrelevant before then.
