### ISSUE TITLE
send load/render-time with petition signature

### ISSUE THREAD

**Issue by schuyler1d** [MoveOnOrg/mop-frontend#363]
We'll have this in google-analytics, etc. as well, but it would be nice to send this back with a petition signature, and maybe even as a parameter to session.json.

This way the backend could monitor/alarm on load-time changes/issues.

I'm not sure the best way to get the load time, but it looks like at least on some browsers `window.performance.timing` has a bunch of moments to measure by/from.

On how this is sent, I would suggest just a random key (`timingPageLoad` or something) at the base of osdiSignature and for session.json, you can similarly send an additional argument `&loadtime=`

**Comment by jparkrr** [comment]
Do you think it should send just for those that landed on the petition sign page? Or for everyone (based on when they actually loaded the app)?

**Comment by schuyler1d** [comment]
Heh, I understand we might just be measuring [where the bullet holes aren't](https://www.motherjones.com/kevin-drum/2010/09/counterintuitive-world/) but I think GA will be good enough for the non-signers.  I just want a number so that we could drill down a little deeper for a sub-cohort if/when we want to.

**Comment by jparkrr** [comment]
If it doesn’t matter too much, I’ll probably not worry about what route they entered on, and just submit the load time until their window load event

**Comment by jparkrr** [comment]
Turns out that `window.performance.timing.loadEventEnd` may not have happened by the time we fire the session.json request, so I'll skip that one for now
