### ISSUE TITLE
trackPage just tracking canonical url

### ISSUE THREAD

**Issue by schuyler1d** [MoveOnOrg/mop-frontend#369]
When I go to https://petitions.moveon.org/2018/sign/stop-censoring-backyard

I get the following in GA debugger (snipped):
```
VM298 analytics_debug.js:10 language         (&ul)   en-us
VM298 analytics_debug.js:10 location         (&dl)   https://petitions.moveon.org/2018/sign/stop-censoring-backyard
VM298 analytics_debug.js:10 page             (&dp)   /sign/stop-censoring-backyard
VM298 analytics_debug.js:10 screenColors     (&sd)   24-bit
```
Note that location is the full/real one, but page is the canonical url.
Let's get it to work and send page correctly here:
https://github.com/MoveOnOrg/mop-frontend/blob/main/src/actions/sessionActions.js#L91
(in both branches)

**Comment by sreynen** [comment]
If I'm understanding this correctly, we want page to include the /2018/ prefix. @schuyler1d please correct if I got that wrong.

**Comment by jparkrr** [comment]
Or can we just send location.href for `page` as well?
