### ISSUE TITLE
petition_id, user_id, medium not sent in some shareclick api calls

### ISSUE THREAD

**Issue by schuyler1d** [MoveOnOrg/mop-frontend#388]
backend is getting some instances of
`{"user_id": null, "petition_id": null, "source": null, "medium": "", "page": "", "mailing": null, "ts_epoch": 1522186720}`
for TRACK_SHARE_URL calls which implies the parameters are not always being sent (some are coming in fine).  It would be good to track down where that is happening.  My guess is it's *one* of the various twitter/facebook/copy things.  It looks like 'email' is definitely working in one case, at least.

**Comment by jparkrr** [comment]
I tried to reproduce it, but I wasn't able to. Can you give a sense of how often it is happening? It seems like this could happen if some browser isn't constructing the POST parameters correctly so all parameters appear as None to the server.

**Comment by schuyler1d** [comment]
ok, i tried reproducing too, and managed to, but it's so dumb I'm tempted to say we should just close this.  If you go directly to:
https://petitions.moveon.org/2018/thanks.html?name=tell-the-senate-block-2
(note that, when actually signing a petition, you'll get a petition_id parameter AND you'll have all the petition data loaded already)

I think if this is the only situation we're talking about, maybe just make sure a petition_id exists and if it doesn't don't send it.  Though I suppose with the JSON data loaded, you should have it, but it might be located elsewhere than the parameter.

**Comment by jparkrr** [comment]
@schuyler1d can you give more detailed reproduction instructions? It still works for me at the url you posted
```
https://petitions.moveon.org/api/v1/share/click

page: /2018/thanks.html
petition_id: 131089
list_id: 131795
medium: email
source: s.em.cp
user_id: 19941473
```

which makes sense, because it loads the petition into the props like you said it should https://github.com/MoveOnOrg/mop-frontend/blob/pass-thirdpartyoptin/src/loaders/thanks-shim.js
and we track based on the petition in the props https://github.com/MoveOnOrg/mop-frontend/blob/pass-thirdpartyoptin/src/containers/thanks.js#L75
and we wouldn't even render the thanks page if the petition couldn't be found.

I guess I'm missing something if you managed to reproduce it though.

**Comment by schuyler1d** [comment]
hm.  is it possible i clicked it before it fully loaded something?  I clicked the email body.

BTW, I noticed that if I click the 'Share Email' button, it doesn't send a shareclick at all.

**Comment by jparkrr** [comment]
I don't think so, as the components don't render until petition was in the state.

And the email button never had tracking in the old rebuild legacy version, so I assumed it was intended. I just checked and it has it in legacy, so I can add it with `source: s.em.mt`

**Comment by schuyler1d** [comment]
weird, i haven't been able to reproduce again, but did see it once.  I'm ok with closing.
