### ISSUE TITLE
Recognized user is prompted for address on non-local petition, should not be

### ISSUE THREAD

**Issue by sreynen** [MoveOnOrg/mop-frontend#395]
Compare https://petitions.moveon.org/2018/sign/tell-facebook-stop-enabling?ak_proof=1&akid=202494.11159533.qi-VxT&rd=1&source=mop&t=13 vs. https://petitions.moveon.org/sign/tell-facebook-stop-enabling?ak_proof=1&akid=202494.11159533.qi-VxT&rd=1&source=mop&t=13

Not entirely sure this is a frontend bug, but suspect it is.

**Comment by jparkrr** [comment]
https://petitions.moveon.org/api/v1/user/session.json?akid=202494.11159533.qi-VxT
Has only given_name and it seems we look for the absence of a user postal address to hide it:
https://github.com/MoveOnOrg/mop-frontend/blob/35768bc3fd6265ffd066fbed6e9effdc3932ef06/src/containers/signature-add-form.js#L260
How should it be?

**Comment by schuyler1d** [comment]
it should only care about the absence of a post_addresses key for petitions where `petition.needs_full_address = true`

**Comment by sreynen** [comment]
I think that line needs something like `&& petition.needs_full_addresses`. The address prompt should only show if it's missing _and_ it's required on the petition. On this example, the petition doesn't require an address, so we don't care if the recognized user doesn't have one.
