### ISSUE TITLE
/2018/ url path tracking to google analytics correctly?

### ISSUE THREAD

**Issue by schuyler1d** [MoveOnOrg/mop-frontend#411]
![petitions-2018path](https://user-images.githubusercontent.com/52117/38441440-ba6abc2a-39b2-11e8-8a11-c2b67b418847.png)

suggests that the thanks page is definitely logging page hits, but it seems that e.g. for the scott-pruit the total GA hits are around 68, instead of the 1000+ for the corresponding hits logged in GA for it.

This suggests we're not reliably tracking the original hits.

**Comment by jparkrr** [comment]
Similar to https://github.com/MoveOnOrg/mop-frontend/issues/369, (tracking canonical url) except on the original html page load

from here https://github.com/MoveOnOrg/mop/blob/main/petitions/templates/petitions/show.html#L8

We should override it here https://github.com/MoveOnOrg/mop/blob/main/petitions/templates/base/base.html#L37
