### ISSUE TITLE
Partner logos not showing on non-mega partner pages

### ISSUE THREAD

**Issue by sreynen** [MoveOnOrg/mop-frontend#413]
https://petitions.moveon.org/sign/vote-on-national-concealed (old version) shows a partner logo.
https://broom.moveon.org/sign/vote-on-national-concealed (new version) does not, but should. 

https://broom.moveon.org/workingfamilies/sign/say-no-to-unqualified-1 shows a partner logo. Looks like we're just doing that only on mega-partner pages (where the URL includes the partner), but need to also do it on non-mega-partner pages (where the URL doesn't change, but the organization exists in the petition metadata).

**Comment by sreynen** [comment]
Note this also needs to change on rebrand version.

**Comment by jparkrr** [comment]
> Note this also needs to change on rebrand version.
I don't think we have partner logos on rebrand. How should this change something there?
