### ISSUE TITLE
Twitter share links missing source tracking on some petitions

### ISSUE THREAD

**Issue by sreynen** [MoveOnOrg/mop-frontend#419]
https://broom.moveon.org/thanks.html?petition_id=95983&name=georgia-add-outkast-to (and also  https://broom.moveon.org/2018r/thanks.html?petition_id=95983&name=georgia-add-outkast-to) both generate links to https://petitions.moveon.org/sign/georgia-add-outkast-to (with no source).

https://broom.moveon.org/thanks.html?petition_id=126869&name=sign-now-demand-congress shares a better link on Twitter, https://broom.moveon.org/p/T_7BW which goes to https://broom.moveon.org/sign/sign-now-demand-congress?from_source=s.tw

**Comment by schuyler1d** [comment]
This might be related to petitions with custom tweet text

**Comment by jparkrr** [comment]
yep. Georgia has that in the petition
```
{
  "facebook_share": {
    "image": "http://s3.moveon.org/images/20150716_outkaststonemountain(1).png",
    "description": "Tell Georgia's legislature: Carve Big Boi and Andre 3000, riding in a Cadillac (as is their wont), into the face of Stone Mountain. Click here to add your name."
  },
  "twitter_share": {
    "message": "Sign&RT: Tell #Georgia: Add #Outkast to #StoneMountain! http://ow.ly/PIlOf @moveon @BigBoi #StankMountain"
  }
}
```

**Comment by sreynen** [comment]
Great, closing.
