### ISSUE TITLE
Facebook share links sometimes super slow

### ISSUE THREAD

**Issue by sreynen** [MoveOnOrg/mop-frontend#420]
This is a pretty vague but report because it's not at all clear to me what's happening, but the core issue is there are some circumstances in which clicking a Facebook share link does nothing for about a minute, and then opens a new tab long so much later that it's totally confusing.

In testing, this doesn't seem to happen on any of the other links. Also, Facebook link seems to be the only one that sometimes gets blocked by popup blockers, but the delay happens even after it's explicitly allowed in popup blockers. And there's still some delay in Firefox, but it seems to be much longer in Chrome.

**Comment by jparkrr** [comment]
Presumably this is related to https://github.com/MoveOnOrg/mop/issues/334, and will be fixed on mop. Ok to close @sreynen @schuyler1d ?

**Comment by jparkrr** [comment]
perhaps I should make it timeout on the frontend too? if so, how much time should I give it?

**Comment by sreynen** [comment]
This doesn't seem to happen on the prod domain, so closing.
