### ISSUE TITLE
Make search route respond to query parameters

### ISSUE THREAD

**Issue by sreynen** [MoveOnOrg/mop-frontend#43]
Current handled parameters are: q, state, and page, maybe more. E.g.: https://petitions.moveon.org/find/?q=taxes&state=CO&page=2

This is currently blocked on https://github.com/MoveOnOrg/mop/issues/48

See also #42.

**Comment by shakalee14** [comment]
Even though this is attached to https://github.com/MoveOnOrg/mop/pull/56, which is why it's blocked, I can still get started on this issue.
