### ISSUE TITLE
Sign the petition button doesn't work when it's at the bottom of the screen

### ISSUE THREAD

**Issue by schuyler1d** [MoveOnOrg/mop-frontend#434]
seen on chrome.
When the sign submit button is at the bottom of the screen, the button isn't clickable.
If I scroll down for it to be more in the middle of the screen then it's clickable.  My guess is there's an invisible fixed div that is stealing the click event. 

![bottomsignbutton](https://user-images.githubusercontent.com/52117/38691813-ee493c96-3e4f-11e8-97c4-a2e0b8014602.png)

**Comment by jparkrr** [comment]
Good find. Will be fixed with this: https://github.com/MoveOnOrg/giraffe/pull/190
