### ISSUE TITLE
Firefox/Safari (not Chrome) redirect /2018r/sign/ petition pages.

### ISSUE THREAD

**Issue by schuyler1d** [MoveOnOrg/mop-frontend#440]
https://broom.moveon.org/2018r/sign/georgia-add-outkast-to
in Firefox loads and then redirects to 
https://petitions.moveon.org/sign/georgia-add-outkast-to
(note the domain change as well) -- looks like some kind of issue with prodReady or similar kind of thing.

**Comment by jparkrr** [comment]
temporary fix: https://github.com/MoveOnOrg/mop-frontend/pull/441

**Comment by schuyler1d** [comment]
it looks like it's tied to reduxImmutableStateInvariant (in `src/store/configureStore.js`)-- that's the only thing that directly changes from PROD=1 (when the other vars are set)  and I've verified that turning that off removes the issue and adding it causes the issue.
