### ISSUE TITLE
Support offline petitions

### ISSUE THREAD

**Issue by schuyler1d** [MoveOnOrg/mop-frontend#448]
See:
https://petitions.moveon.org/sign/nra-board-member-rep
looks like
![offlinepetition](https://user-images.githubusercontent.com/52117/38819671-05bd9d28-416a-11e8-8f90-df2595a9d70b.png)

The petitions api has a property `petitions.online` -- when that is === `0` or `false` then we should display this instead.  Furthermore, besides name, id, etc, no other petition data should be expected to exist.

**Comment by schuyler1d** [comment]
Note also, this doesn't currently work, because on prod we are preloading.  however this should also be shown when it hits the API for the sign data and gets:
{"response_code":404,"error_code":"petition_unavailable","description":"This petition has been taken down."}

**Comment by jparkrr** [comment]
Sorry, I get it now. I should handle offline petitions in different ways whether they are preloaded or fetched with ajax.

**Comment by jparkrr** [comment]
Will look like this on giraffe.

<img width="835" alt="image" src="https://user-images.githubusercontent.com/872456/38994072-5ffc4104-43b3-11e8-9940-4adb3a4aba9d.png">
