### ISSUE TITLE
Validation discrepancy: "You must select at least one target for your petition" 

### ISSUE THREAD

**Issue by Dayologic** [MoveOnOrg/mop-frontend#452]
Description: While creating a petition - should the user opt to select "State Governor" as a target then proceed to PREVIEW the petition, selecting the "back" button leaves "Governor of State" target selected without a State being associated to the Governor.  Selecting PREVIEW with this target generates a message that can be confusing to the user "as a target is selected."

ENV: STG
Browser: Chrome (latest)
OS: macOS Sierra 10.12.5
Priority: LOW

Steps To Reproduce:

1) Navigate to: https://petitions.moveon.org/2018r/
2) Fill out the petition form with all relevant data
3) In "Who's The Target Of Your Petition?" Section Select a "State" and Select "Governor Of State" Options
4) Select "Preview Petition"
5) Select the "Back" button
6) Select "Preview Petition" Again

Expected Result: The target section should be cleared of all selections - or prior selection should be retained in it's entirety

Actual Result: The target section is partially cleared so that when the user selects "Preview Petition" - an error message instructing the user to select a target is generated even though a target remains pre-selected

SCREENSHOT:
<img width="1680" alt="target" src="https://user-images.githubusercontent.com/19258160/38842054-94afecb6-41b5-11e8-8eee-97e4549e25a4.png">

**Comment by jparkrr** [comment]
This one will probably be fixed with the rebuild. When you select something like "Governor of Arkansas", it will retain that specific state governor in the local state before it's submitted. I'll verify once `/create_revise.html` is built.
