### ISSUE TITLE
STORE/SOCIAL: Product Name/description/Images Not Rendered When Shared on Twitter

### ISSUE THREAD

**Issue by Dayologic** [MoveOnOrg/mop-frontend#470]
Description: When a product is shared on twitter, the associated name/description/image is not rendered/displayed

ENV: STG
Browser: Chrome (latest)
OS: macOS Sierra 10.12.5
Priority: LOW

Steps To Reproduce:

1) Navigate to: https://front-stage.moveon.org/
2) Select "Store" from the top men
3) Ensure you're logged into Twitter
4) Select a product from the product page (ie: GET BERNIE SANDERS' NEW BOOK AND SUPPORT MOVEON'S FIGHT AGAINST TRUMP, STICKER PACKS: OUR DREAMS UNITE US)
5) Select the twitter icon under the product description
6) In the new tab - select "Tweet"

Expected Result: The associated product name/description/images are shared on twitter - optimally in a large card

Actual Result: The associated product name/description/images are not shared on twitter - but the verbiage of another product is displayed

SCREENSHOT:
<img width="1675" alt="twitter_store" src="https://user-images.githubusercontent.com/19258160/39010577-0ae80700-43dd-11e8-8fa3-756aebfed6db.png">

**Comment by schuyler1d** [comment]
Closing since this is related to the store.
