### ISSUE TITLE
MOVEON: "Store" link in header is inactive

### ISSUE THREAD

**Issue by Dayologic** [MoveOnOrg/mop-frontend#477]
Description: Clicking on the "Store" link in the header has no effect - link appears to be inactive.

ENV: STG
Browser: Chrome (latest)
OS: macOS Sierra 10.12.5
Priority: LOW

Steps To Reproduce:

1) Navigate to: broom.moveon.org/
2) Select "Store" from the top menu

Expected Result: The user is taken to the MoveOn Store

Actual Result: The link appears to be inactive

SCREENSHOT:
<img width="1668" alt="screen shot 2018-04-23 at 3 48 04 pm" src="https://user-images.githubusercontent.com/19258160/39149973-d4ba9942-470e-11e8-8434-e7bc1507d18c.png">

**Comment by jparkrr** [comment]
Thanks, good find! Found the problem. Will fix shortly.

**Comment by jparkrr** [comment]
The bug was such that it worked when the current path included "/2018r/", but not at a base domain.
