### ISSUE TITLE
Twitter cards still rendering old logo

### ISSUE THREAD

**Issue by sandramchung** [MoveOnOrg/mop-frontend#494]
Twitter cards are the previews you get when you share links on twitter.
You can check them at https://cards-dev.twitter.com/validator 
Every sign page URL I enter pulls the old logo.

**Comment by jparkrr** [comment]
Needs to be updated here https://github.com/MoveOnOrg/mop/blob/751fd2f0e5d918cc525a0130b5545a3f411f9991/petitions/template_context.py#L21
