### ISSUE TITLE
MOVEON: Collapse mobile menu upon user selection?

### ISSUE THREAD

**Issue by Dayologic** [MoveOnOrg/mop-frontend#503]
Description: Selecting the mobile menu displays a full screen menu takeover.  Should the user already be on a selected page - making the same selection keeps the menu expanded.

ENV: STG
Device: iPad - 5th Edition
Browser: Safari (latest)
OS: iOS Sierra v11
Priority: LOW

Steps To Reproduce:

1) On an iPad Navigate to: front.moveon.org
2) From the mobile menu - select "Petitions"
3) Select "Browse Petitions"
4) From the mobile menu - select again "Petitions"
5) Then Select "Browse Petitions"

Expected Result: The menu collapses and the user is taken to the appropriate page

Actual Result: The menu remains expanded until the user closes the menu.  This could errantly give the impression that the link is inactive.

Screenshot 1:
<img width="1232" alt="menu_expanded" src="https://user-images.githubusercontent.com/19258160/39269954-73981370-48a2-11e8-9e5c-d484dbb7b8ef.png">

**Comment by jparkrr** [comment]
ah yeah, I forgot about this. I can fix it pretty easily. Thanks for finding it.

**Comment by Dayologic** [comment]
Thanks @jparkrr !!
