### ISSUE TITLE
[Comp] - SMS Signup on Petition Signing

### ISSUE THREAD

**Issue by shakalee14** [MoveOnOrg/mop-frontend#511]
**Purpose**: We want to run an a/b test for adding a phone number field (called 'mobile') for petition signing. When that phone number is filled - we want to have a mobile opt in box/language appear. The phone number will not be required.

**Mobile field placement:** In between zip code and comment field 
and then the mobile opt in language appears (after phone number is filled in) below the phone number and above the comment field.

**Devices**: Desktop, tablet, mobile

**Helpful Context**:
Mobile opt in language can be found [here](https://front.moveon.org/#join)

Petition Signing (currently doesn't have a phone number field).
https://petitions.moveon.org/sign/cancel-faleena-hopkins?source=petitionshomepage

Mobile Opt in Language (will be the same language because of legal):
https://front.moveon.org/#join

**Comment by hi0ctane** [comment]
@shakalee14 attached are the comps. the large comp works for both mobile and desktop. The mobile optin language wraps a bit on mobile but thats unavoidable. 

only a suggestion and very low priority:
In regards to behavior I think its best to only enable the opt-in checkbox on mobile field validation. 
Its an odd scenario and unlikely to happen but on front.moveon.org i was able to check the mobile opt-in without entering any mobile number. 

**desktop-tablet:**
![mobile-opt-in-petition-desktop-tablet](https://user-images.githubusercontent.com/5332564/39869807-ea90e340-542c-11e8-81da-d27729b50a13.jpg)


**mobile:**
![mobile-opt-in-petition-mobile](https://user-images.githubusercontent.com/5332564/39869806-ea6cd2e8-542c-11e8-8f06-72381d41d8c4.jpg)
