### ISSUE TITLE
Add Mobile Field with Opt In Language for Petition Signing

### ISSUE THREAD

**Issue by shakalee14** [MoveOnOrg/mop-frontend#512]
On the sign petition form
- [x] Add phone number field (where it is not required in order to sign a petition)
- [x] When values are added in that phone number field -> show checkbox with mobile opt in language
- When number is provided and opt in box is checked 
   - [x] Post to AK for sms_subscribed (sky will handle this in [mop](https://github.com/MoveOnOrg/mop/issues/389))
   - [ ] Post to revere api to get immediate text

- [x] Deploy a/b test - 50% of folks to see the phone field/checkbox  & 50% of folks to see current form

Context from @schuyler1d - work will be happening here:
- src/containers/signature-add-form.js
- test/components/signature-add-form.js
- src/components/theme-giraffe/signature-add-form.js

**Comment by shakalee14** [comment]
Comps here: https://github.com/MoveOnOrg/mop-frontend/issues/511

**Comment by schuyler1d** [comment]
personal feedback from the comps: "Mobile Opt-in" isn't quite clear that it's a phone number field.  Maybe "Mobile Phone (optional)" or at least placeholder text of the form (xxx-xxx-xxxx or 123-123-1234).
Not sure we can do this, but at least when someone starts entering their number, maybe it auto-checks the optin box?

**Comment by shakalee14** [comment]
@schuyler1d  talked to Mark and we're using 'Mobile' from now on across the site (it was updated in our wp sites)
Currently, the opt in language appears after someone starts typing in mobile. I'm down for a placeholder and down for it starting as checked.

**Comment by shakalee14** [comment]
Noting though - on the comps, I've made the decision to keep the opt in text grey to match the rest of the forms' opt in texts

**Comment by shakalee14** [comment]
Handled and tested with :
https://github.com/MoveOnOrg/mop-frontend/pull/549
https://github.com/MoveOnOrg/mop-frontend/pull/525
https://github.com/MoveOnOrg/mop-frontend/pull/580

After rounds of live testing with petitions - it's been decided to add the mobile field.
