### ISSUE TITLE
Petition creation form submission throws confusing error when only a custom target is selected

### ISSUE THREAD

**Issue by sandramchung** [MoveOnOrg/mop-frontend#550]
<img width="587" alt="moveon_petitions_-_sign_or_start_a_petition_and_developer_tools_-_https___broom_moveon_org_2018_create_start_html_and_1password" src="https://user-images.githubusercontent.com/5560919/41122687-956f3202-6a59-11e8-9b20-8ad69a76cc03.png">
It works if I then click "add another target" and re-submit.

**Comment by jparkrr** [comment]
Good catch. I misunderstood how this was supposed to work.
