### ISSUE TITLE
After a logged-in user has previewed a new petition, post it to the backend

### ISSUE THREAD

**Issue by jparkrr** [MoveOnOrg/mop-frontend#552]
We can detect the user session on the preview page, and provide a "Launch Petition" button that submits the petition instead of the RegisterForm. The petition endpoint will read their session, so no user information will need to be provided by the frontend.

One wrinkle is we might need to provide the zip code for the user if not present, as mentioned here  https://github.com/MoveOnOrg/mop/issues/415

**Comment by sandramchung** [comment]
MoveOnOrg/mop#415 is done, so no more backend blockers on this one.

**Comment by schuyler1d** [comment]
One other note -- if the user has an akid / guest login but is not authenticated, then we will also need to ask them to set a password, but don't need to ask name/etc.  Not sure how it works currently.

**Comment by jparkrr** [comment]
Paraphrased from @schuyler1d on slack:
> so actually it looks like in theory it accepts an id= parameter but when it does that it doesn't require login/password at all.  However I also don't see that link generated anywhere in the code base and it sounds like everyone has to fill out that info -- i.e. we don't have akid= parameters anywhere
>
> so I'm tempted to say we should scrap this as a use-case -- at least for now
>
>So to be clear, I think for now the logic should be if `userStore.authenticated` then just go ahead and submit the petition without prompting for data, but if the session info is just based on an akid, then prompt the user for all the data.
I suppose if they've navigated after signing a petition and you have userStore.name you can autofill in that, etc to the create form

So I'll close this issue from #562. Feel free to open more issues if you would like the functionality to go further.
