### ISSUE TITLE
Track petition creation in google analytics

### ISSUE THREAD

**Issue by schuyler1d** [MoveOnOrg/mop-frontend#556]
Similar code to:
https://github.com/MoveOnOrg/mop-frontend/blob/main/src/actions/petitionActions.js#L170-L173
needs to occur for a configured gtag id for petition creation.  This could be from a global/window variable and/or from a Config option (any thoughts/preferences?)

It should be called when a petition was successfully created.

**Comment by jparkrr** [comment]
Having it in Config seems slightly better to me
