### ISSUE TITLE
Add Permanent Mobile Field and Opt In Box for Petition Signers

### ISSUE THREAD

**Issue by shakalee14** [MoveOnOrg/mop-frontend#585]
Related to testing involved with : https://github.com/MoveOnOrg/mop-frontend/issues/512

Need to add the mobile field but remove testing part (cohort etc)

@schuyler1d - is it worth keeping the cohort logic somewhere for future tests (i could put it into a doc) or i could keep the testFn(), add comments https://github.com/MoveOnOrg/mop-frontend/blob/main/src/routes.js#L92 and then just take all the testing pieces out.

**Comment by schuyler1d** [comment]
Yes!  Take a look at: https://github.com/MoveOnOrg/mop-frontend/pull/577
Not sure you want to divert focus to the tracking stuff, in general, but take a look at the documentation that was added to that PR:
https://github.com/MoveOnOrg/mop-frontend/blob/f303f7caa3e02359c682aa9a12e3b8f1b0b93be0/src/lib/form-tracker.js#L9
and possibly update/review it.  Anything missing or useful, please add to.
