### ISSUE TITLE
Add page and components for megapartner home pages

### ISSUE THREAD

**Issue by sreynen** [MoveOnOrg/mop-frontend#69]
Should be able to load /:partner-name URLs and get generally the same content seen on the legacy site, e.g. http://petitions.moveon.org/americasvoice/ For the context of this issue, it doesn't need to be an exact match (though that would be great), just close enough that we can easily note the remaining work in more specific issues.

Most of this content is already in the home page, but needs to send the megapartner param to the API in this context.

**Comment by schuyler1d** [comment]
I'm working a bit on the nav for this in the context of the sign/thanks page.  Ping me if you start working on this.

**Comment by schuyler1d** [comment]
When I tied this issue to the PR above, I thought it was just the components, but still todo is the pages themselves
