### ISSUE TITLE
Billboard formatting doesn't quite match legacy site

### ISSUE THREAD

**Issue by sreynen** [MoveOnOrg/mop-frontend#82]
Should look like this:
<img width="951" alt="screen shot 2017-12-04 at 12 14 28 pm" src="https://user-images.githubusercontent.com/108645/33571310-dd0ab90a-d8ec-11e7-8273-dcdfde8ee688.png">

But currently looks like this:
<img width="949" alt="screen shot 2017-12-04 at 12 14 35 pm" src="https://user-images.githubusercontent.com/108645/33571328-eced7c40-d8ec-11e7-9195-203ec46415bb.png">

Specifically, the video size and the text sizes are slightly different different.

**Comment by shakalee14** [comment]
making a note that currently the billboard section in petitions.moveon.org looks different depending on browser (font is bigger in chrome vs. firefox)
